/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author dmich
 */
public class CreateWorkSite extends javax.swing.JPanel {

    /**
     * Creates new form workSiteDashboard
     */
    public CreateWorkSite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        taskTitle = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        locationLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        locationInfoTitle = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        streetField = new javax.swing.JTextField();
        streetNoField = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        postalCodeField = new javax.swing.JTextField();
        townLabel = new javax.swing.JLabel();
        townField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        collectedProduceBtn = new javax.swing.JButton();
        addWorkersBtn = new javax.swing.JButton();
        scrollableListContainer = new javax.swing.JScrollPane();
        workerList = new javax.swing.JList<>();
        cancelBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1000, 720));
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(120, 168, 252));
        topBar.setPreferredSize(new java.awt.Dimension(1000, 110));

        taskTitle.setBackground(new java.awt.Color(249, 249, 249));
        taskTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        taskTitle.setForeground(new java.awt.Color(249, 249, 249));
        taskTitle.setText("Create new work site");
        taskTitle.setPreferredSize(new java.awt.Dimension(450, 50));

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
                topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topBarLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(taskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(523, Short.MAX_VALUE))
        );
        topBarLayout.setVerticalGroup(
                topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topBarLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(taskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainContainer.setBackground(new java.awt.Color(71, 120, 197));

        locationLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(249, 249, 249));
        locationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_place_marker_32px.png"))); // NOI18N
        locationLabel.setText("Name");
        locationLabel.setFocusable(false);

        locationField.setText("Name of the location");
        locationField.setMinimumSize(new java.awt.Dimension(65, 26));
        locationField.setPreferredSize(new java.awt.Dimension(65, 26));
        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(249, 249, 249));
        cityLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_place_marker_32px.png"))); // NOI18N
        cityLabel.setText("City");
        cityLabel.setFocusable(false);

        cityField.setText("City");
        cityField.setMinimumSize(new java.awt.Dimension(65, 26));
        cityField.setPreferredSize(new java.awt.Dimension(65, 26));
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        locationInfoTitle.setText("Location information:");

        streetLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        streetLabel.setForeground(new java.awt.Color(249, 249, 249));
        streetLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_place_marker_32px.png"))); // NOI18N
        streetLabel.setText("Street");
        streetLabel.setFocusable(false);

        streetField.setText("Streetname");
        streetField.setToolTipText("");
        streetField.setMinimumSize(new java.awt.Dimension(65, 26));
        streetField.setPreferredSize(new java.awt.Dimension(65, 26));
        streetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetFieldActionPerformed(evt);
            }
        });

        streetNoField.setText("No.");
        streetNoField.setMinimumSize(new java.awt.Dimension(65, 26));
        streetNoField.setPreferredSize(new java.awt.Dimension(65, 26));
        streetNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNoFieldActionPerformed(evt);
            }
        });

        postalCodeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        postalCodeLabel.setForeground(new java.awt.Color(249, 249, 249));
        postalCodeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_place_marker_32px.png"))); // NOI18N
        postalCodeLabel.setText("Postal code");
        postalCodeLabel.setFocusable(false);

        postalCodeField.setText("Postal code");
        postalCodeField.setMinimumSize(new java.awt.Dimension(65, 26));
        postalCodeField.setPreferredSize(new java.awt.Dimension(65, 26));
        postalCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeFieldActionPerformed(evt);
            }
        });

        townLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        townLabel.setForeground(new java.awt.Color(249, 249, 249));
        townLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_place_marker_32px.png"))); // NOI18N
        townLabel.setText("Town");
        townLabel.setFocusable(false);

        townField.setText("Town");
        townField.setMinimumSize(new java.awt.Dimension(65, 26));
        townField.setPreferredSize(new java.awt.Dimension(65, 26));
        townField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townFieldActionPerformed(evt);
            }
        });

        descriptionLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(249, 249, 249));
        descriptionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_place_marker_32px.png"))); // NOI18N
        descriptionLabel.setText("Description");
        descriptionLabel.setFocusable(false);

        descriptionField.setText("Description");
        descriptionField.setMinimumSize(new java.awt.Dimension(65, 26));
        descriptionField.setPreferredSize(new java.awt.Dimension(65, 26));
        descriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionFieldActionPerformed(evt);
            }
        });

        collectedProduceBtn.setBackground(new java.awt.Color(71, 120, 197));
        collectedProduceBtn.setText("Collected Produce");

        addWorkersBtn.setBackground(new java.awt.Color(71, 120, 197));
        addWorkersBtn.setText("Add/Edit workers");
        addWorkersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWorkersBtnActionPerformed(evt);
            }
        });

        workerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollableListContainer.setViewportView(workerList);

        cancelBtn.setBackground(new java.awt.Color(71, 120, 197));
        cancelBtn.setText("Cancel");

        createBtn.setBackground(new java.awt.Color(71, 120, 197));
        createBtn.setText("Create");

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
                mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(locationInfoTitle)
                                        .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainContainerLayout.createSequentialGroup()
                                                        .addComponent(cityLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(mainContainerLayout.createSequentialGroup()
                                                        .addComponent(locationLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainContainerLayout.createSequentialGroup()
                                                        .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(postalCodeLabel)
                                                                .addComponent(streetLabel))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(townField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(mainContainerLayout.createSequentialGroup()
                                                                        .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(streetNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(townLabel)
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(descriptionLabel)
                                                .addGap(18, 18, 18)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(collectedProduceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(descriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addWorkersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContainerLayout.createSequentialGroup()
                                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(scrollableListContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49))
        );
        mainContainerLayout.setVerticalGroup(
                mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(locationLabel)
                                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addWorkersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(locationInfoTitle)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cityLabel)
                                                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(streetLabel)
                                                        .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(streetNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(postalCodeLabel)
                                                        .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(42, 42, 42)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(townLabel)
                                                        .addComponent(townField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(descriptionLabel)
                                                        .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(scrollableListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(collectedProduceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(mainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1000, 610));
    }// </editor-fold>

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void streetFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void postalCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void townFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void descriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addWorkersBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void streetNoFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton addWorkersBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton collectedProduceBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel locationInfoTitle;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JScrollPane scrollableListContainer;
    private javax.swing.JTextField streetField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetNoField;
    private javax.swing.JLabel taskTitle;
    private javax.swing.JPanel topBar;
    private javax.swing.JTextField townField;
    private javax.swing.JLabel townLabel;
    private javax.swing.JList<String> workerList;
    // End of variables declaration
}
