/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.*;

public class Dashboard extends JPanel {

    /**
     * Creates new form dashboard
     */
    public Dashboard() {
        initComponents();
        registerTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overviewPane = new javax.swing.JPanel();
        overviewProfile = new javax.swing.JPanel();
        overviewBtns = new javax.swing.JPanel();
        mailBtn = new javax.swing.JLabel();
        contactsBtn = new javax.swing.JLabel();
        calendarBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exitBtn = new javax.swing.JLabel();
        profileNameLabel = new javax.swing.JLabel();
        profilePicture = new javax.swing.JLabel();
        viewTaskBtn = new javax.swing.JButton();
        readableDayLabel = new javax.swing.JLabel();
        monthYearLabel = new javax.swing.JLabel();
        registerTaskBtn = new javax.swing.JButton();
        contactLeaderBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workTaskListTable = new javax.swing.JTable();
        registerWorkTask1 = new RegisterWorkTask();
        jPanel1 = new javax.swing.JPanel();
        overviewPane1 = new javax.swing.JPanel();
        overviewProfile1 = new javax.swing.JPanel();
        overviewBtns1 = new javax.swing.JPanel();
        mailBtn1 = new javax.swing.JLabel();
        contactsBtn1 = new javax.swing.JLabel();
        calendarBtn1 = new javax.swing.JLabel();
        logoutBtn1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        exitBtn1 = new javax.swing.JLabel();
        profileNameLabel1 = new javax.swing.JLabel();
        profilePicture1 = new javax.swing.JLabel();
        viewTaskBtn1 = new javax.swing.JButton();
        readableDayLabel1 = new javax.swing.JLabel();
        monthYearLabel1 = new javax.swing.JLabel();
        registerTaskBtn1 = new javax.swing.JButton();
        contactLeaderBtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workTaskListTable1 = new javax.swing.JTable();
        registerWorkTask2 = new RegisterWorkTask();

        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overviewPane.setBackground(new java.awt.Color(71, 120, 197));

        overviewProfile.setBackground(new java.awt.Color(120, 168, 252));
        overviewProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overviewBtns.setBackground(new java.awt.Color(84, 127, 206));

        mailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_secured_letter_32px_3.png"))); // NOI18N

        contactsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_contacts_32px.png"))); // NOI18N

        calendarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_calendar_32px.png"))); // NOI18N

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_lock_32px.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout overviewBtnsLayout = new javax.swing.GroupLayout(overviewBtns);
        overviewBtns.setLayout(overviewBtnsLayout);
        overviewBtnsLayout.setHorizontalGroup(
            overviewBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewBtnsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(overviewBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(overviewBtnsLayout.createSequentialGroup()
                        .addComponent(mailBtn)
                        .addGap(37, 37, 37)
                        .addComponent(contactsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(calendarBtn)
                        .addGap(36, 36, 36)
                        .addComponent(logoutBtn)))
                .addGap(37, 37, 37))
        );
        overviewBtnsLayout.setVerticalGroup(
            overviewBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewBtnsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(overviewBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailBtn)
                    .addComponent(contactsBtn)
                    .addComponent(calendarBtn)
                    .addComponent(logoutBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        overviewProfile.add(overviewBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, -1, -1));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_exit_32px.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
        });
        overviewProfile.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        profileNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        profileNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileNameLabel.setText("John Doe");
        overviewProfile.add(profileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_github_96px.png"))); // NOI18N
        profilePicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profilePictureMousePressed(evt);
            }
        });
        overviewProfile.add(profilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 100));

        viewTaskBtn.setText("View Task");
        viewTaskBtn.setBackground(new java.awt.Color(71, 120, 197));
        viewTaskBtn.setBorder(null);
        viewTaskBtn.setForeground(new java.awt.Color(255, 255, 255));

        readableDayLabel.setText("Wednesday 13");
        readableDayLabel.setForeground(new java.awt.Color(255, 255, 255));

        monthYearLabel.setText("May 2020");
        monthYearLabel.setForeground(new java.awt.Color(255, 255, 255));

        registerTaskBtn.setText("Register Task");
        registerTaskBtn.setBackground(new java.awt.Color(71, 120, 197));
        registerTaskBtn.setBorder(null);
        registerTaskBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTaskBtnActionPerformed(evt);
            }
        });

        contactLeaderBtn.setText("Contact Leader");
        contactLeaderBtn.setBackground(new java.awt.Color(71, 120, 197));
        contactLeaderBtn.setBorder(null);
        contactLeaderBtn.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout overviewPaneLayout = new javax.swing.GroupLayout(overviewPane);
        overviewPane.setLayout(overviewPaneLayout);
        overviewPaneLayout.setHorizontalGroup(
            overviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overviewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(overviewPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTaskBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(overviewPaneLayout.createSequentialGroup()
                        .addComponent(readableDayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(monthYearLabel))
                    .addComponent(contactLeaderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerTaskBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        overviewPaneLayout.setVerticalGroup(
            overviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPaneLayout.createSequentialGroup()
                .addComponent(overviewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(overviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readableDayLabel)
                    .addComponent(monthYearLabel))
                .addGap(18, 18, 18)
                .addComponent(registerTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactLeaderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        add(overviewPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 720));

        workTaskListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11/05/2020", "1",  new Integer(120),  new Boolean(true)},
                {"12/05/2020", "1",  new Integer(140),  new Boolean(false)},
                {"13/05/2020", "2",  new Integer(100),  new Boolean(true)},
                {"14/05/2020", "3",  new Integer(90), null}
            },
            new String [] {
                "Date", "Site", "Quantity", "Approved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workTaskListTable.setForeground(new java.awt.Color(102, 102, 102));
        workTaskListTable.setGridColor(new java.awt.Color(255, 255, 255));
        workTaskListTable.setRowHeight(32);
        workTaskListTable.setSelectionBackground(new java.awt.Color(0, 120, 215));
        jScrollPane1.setViewportView(workTaskListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 690, 720));
        add(registerWorkTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overviewPane1.setBackground(new java.awt.Color(71, 120, 197));

        overviewProfile1.setBackground(new java.awt.Color(120, 168, 252));
        overviewProfile1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overviewBtns1.setBackground(new java.awt.Color(84, 127, 206));

        mailBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_secured_letter_32px_3.png"))); // NOI18N

        contactsBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_contacts_32px.png"))); // NOI18N

        calendarBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_calendar_32px.png"))); // NOI18N

        logoutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_lock_32px.png"))); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout overviewBtns1Layout = new javax.swing.GroupLayout(overviewBtns1);
        overviewBtns1.setLayout(overviewBtns1Layout);
        overviewBtns1Layout.setHorizontalGroup(
            overviewBtns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewBtns1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(overviewBtns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(overviewBtns1Layout.createSequentialGroup()
                        .addComponent(mailBtn1)
                        .addGap(37, 37, 37)
                        .addComponent(contactsBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(calendarBtn1)
                        .addGap(36, 36, 36)
                        .addComponent(logoutBtn1)))
                .addGap(37, 37, 37))
        );
        overviewBtns1Layout.setVerticalGroup(
            overviewBtns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewBtns1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(overviewBtns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailBtn1)
                    .addComponent(contactsBtn1)
                    .addComponent(calendarBtn1)
                    .addComponent(logoutBtn1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        overviewProfile1.add(overviewBtns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, -1, -1));

        exitBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_exit_32px.png"))); // NOI18N
        exitBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtn1MousePressed(evt);
            }
        });
        overviewProfile1.add(exitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        profileNameLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        profileNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        profileNameLabel1.setText("John Doe");
        overviewProfile1.add(profileNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        profilePicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_github_96px.png"))); // NOI18N
        profilePicture1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profilePicture1MousePressed(evt);
            }
        });
        overviewProfile1.add(profilePicture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 100));

        viewTaskBtn1.setBackground(new java.awt.Color(71, 120, 197));
        viewTaskBtn1.setForeground(new java.awt.Color(255, 255, 255));
        viewTaskBtn1.setText("View Task");
        viewTaskBtn1.setBorder(null);

        readableDayLabel1.setForeground(new java.awt.Color(255, 255, 255));
        readableDayLabel1.setText("Wednesday 13");

        monthYearLabel1.setForeground(new java.awt.Color(255, 255, 255));
        monthYearLabel1.setText("May 2020");

        registerTaskBtn1.setBackground(new java.awt.Color(71, 120, 197));
        registerTaskBtn1.setForeground(new java.awt.Color(255, 255, 255));
        registerTaskBtn1.setText("Register Task");
        registerTaskBtn1.setBorder(null);
        registerTaskBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTaskBtn1ActionPerformed(evt);
            }
        });

        contactLeaderBtn1.setBackground(new java.awt.Color(71, 120, 197));
        contactLeaderBtn1.setForeground(new java.awt.Color(255, 255, 255));
        contactLeaderBtn1.setText("Contact Leader");
        contactLeaderBtn1.setBorder(null);

        javax.swing.GroupLayout overviewPane1Layout = new javax.swing.GroupLayout(overviewPane1);
        overviewPane1.setLayout(overviewPane1Layout);
        overviewPane1Layout.setHorizontalGroup(
            overviewPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overviewProfile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(overviewPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTaskBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(overviewPane1Layout.createSequentialGroup()
                        .addComponent(readableDayLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(monthYearLabel1))
                    .addComponent(contactLeaderBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerTaskBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        overviewPane1Layout.setVerticalGroup(
            overviewPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPane1Layout.createSequentialGroup()
                .addComponent(overviewProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(overviewPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readableDayLabel1)
                    .addComponent(monthYearLabel1))
                .addGap(18, 18, 18)
                .addComponent(registerTaskBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewTaskBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactLeaderBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jPanel1.add(overviewPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 720));

        workTaskListTable1.setForeground(new java.awt.Color(102, 102, 102));
        workTaskListTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11/05/2020", "1",  new Integer(120),  new Boolean(true)},
                {"12/05/2020", "1",  new Integer(140),  new Boolean(false)},
                {"13/05/2020", "2",  new Integer(100),  new Boolean(true)},
                {"14/05/2020", "3",  new Integer(90), null}
            },
            new String [] {
                "Date", "Site", "Quantity", "Approved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workTaskListTable1.setGridColor(new java.awt.Color(255, 255, 255));
        workTaskListTable1.setRowHeight(32);
        workTaskListTable1.setSelectionBackground(new java.awt.Color(0, 120, 215));
        jScrollPane2.setViewportView(workTaskListTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 690, 720));
        jPanel1.add(registerWorkTask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitBtnMousePressed

    private void profilePictureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictureMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictureMousePressed

    private void registerTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTaskBtnActionPerformed
        jScrollPane1.setVisible(false);
        registerTask();

    }//GEN-LAST:event_registerTaskBtnActionPerformed

    private void registerTaskBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTaskBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerTaskBtn1ActionPerformed

    private void profilePicture1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePicture1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePicture1MousePressed

    private void exitBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtn1MousePressed

    private void registerTask(){
        if(registerWorkTask1.isVisible()){
            registerWorkTask1.setVisible(false);
        }else{
            registerWorkTask1.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calendarBtn;
    private javax.swing.JLabel calendarBtn1;
    private javax.swing.JButton contactLeaderBtn;
    private javax.swing.JButton contactLeaderBtn1;
    private javax.swing.JLabel contactsBtn;
    private javax.swing.JLabel contactsBtn1;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel exitBtn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel logoutBtn1;
    private javax.swing.JLabel mailBtn;
    private javax.swing.JLabel mailBtn1;
    private javax.swing.JLabel monthYearLabel;
    private javax.swing.JLabel monthYearLabel1;
    private javax.swing.JPanel overviewBtns;
    private javax.swing.JPanel overviewBtns1;
    private javax.swing.JPanel overviewPane;
    private javax.swing.JPanel overviewPane1;
    private javax.swing.JPanel overviewProfile;
    private javax.swing.JPanel overviewProfile1;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JLabel profileNameLabel1;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JLabel profilePicture1;
    private javax.swing.JLabel readableDayLabel;
    private javax.swing.JLabel readableDayLabel1;
    private javax.swing.JButton registerTaskBtn;
    private javax.swing.JButton registerTaskBtn1;
    private RegisterWorkTask registerWorkTask1;
    private RegisterWorkTask registerWorkTask2;
    private javax.swing.JButton viewTaskBtn;
    private javax.swing.JButton viewTaskBtn1;
    private javax.swing.JTable workTaskListTable;
    private javax.swing.JTable workTaskListTable1;
    // End of variables declaration//GEN-END:variables
}
