/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author dmich
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        updateDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        sidePanelBtnHome = new javax.swing.JPanel();
        ind = new javax.swing.JPanel();
        homeBtnLabel = new javax.swing.JLabel();
        sidePanelBtnUsers = new javax.swing.JPanel();
        ind1 = new javax.swing.JPanel();
        usersBtnLabel = new javax.swing.JLabel();
        sidePanelBtnProfile = new javax.swing.JPanel();
        ind2 = new javax.swing.JPanel();
        profileBtnLabel = new javax.swing.JLabel();
        sidePanelBtnSettings = new javax.swing.JPanel();
        ind3 = new javax.swing.JPanel();
        settingsBtnLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JLabel();
        dashboard2 = new Dashboard();
        loginScreen2 = new loginScreen();
        workSiteDashboard1 = new workSiteDashboard();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Herbal Time");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(123, 156, 225));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(23, 35, 51));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelBtnHome.setBackground(new java.awt.Color(23, 35, 51));
        sidePanelBtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelBtnHomeMousePressed(evt);
            }
        });

        ind.setBackground(new java.awt.Color(204, 204, 204));
        ind.setOpaque(false);
        ind.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout indLayout = new javax.swing.GroupLayout(ind);
        ind.setLayout(indLayout);
        indLayout.setHorizontalGroup(
            indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        indLayout.setVerticalGroup(
            indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homeBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeBtnLabel.setText("Home");

        javax.swing.GroupLayout sidePanelBtnHomeLayout = new javax.swing.GroupLayout(sidePanelBtnHome);
        sidePanelBtnHome.setLayout(sidePanelBtnHomeLayout);
        sidePanelBtnHomeLayout.setHorizontalGroup(
            sidePanelBtnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelBtnHomeLayout.createSequentialGroup()
                .addComponent(ind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(homeBtnLabel)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        sidePanelBtnHomeLayout.setVerticalGroup(
            sidePanelBtnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelBtnHomeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(homeBtnLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidePanel.add(sidePanelBtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 50));

        sidePanelBtnUsers.setBackground(new java.awt.Color(23, 35, 51));
        sidePanelBtnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelBtnUsersMousePressed(evt);
            }
        });

        ind1.setBackground(new java.awt.Color(204, 204, 204));
        ind1.setOpaque(false);
        ind1.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout ind1Layout = new javax.swing.GroupLayout(ind1);
        ind1.setLayout(ind1Layout);
        ind1Layout.setHorizontalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind1Layout.setVerticalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usersBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        usersBtnLabel.setText("Employees");

        javax.swing.GroupLayout sidePanelBtnUsersLayout = new javax.swing.GroupLayout(sidePanelBtnUsers);
        sidePanelBtnUsers.setLayout(sidePanelBtnUsersLayout);
        sidePanelBtnUsersLayout.setHorizontalGroup(
            sidePanelBtnUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelBtnUsersLayout.createSequentialGroup()
                .addComponent(ind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(usersBtnLabel)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        sidePanelBtnUsersLayout.setVerticalGroup(
            sidePanelBtnUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelBtnUsersLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(usersBtnLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidePanel.add(sidePanelBtnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        sidePanelBtnProfile.setBackground(new java.awt.Color(23, 35, 51));
        sidePanelBtnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelBtnProfileMousePressed(evt);
            }
        });

        ind2.setBackground(new java.awt.Color(204, 204, 204));
        ind2.setOpaque(false);
        ind2.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout ind2Layout = new javax.swing.GroupLayout(ind2);
        ind2.setLayout(ind2Layout);
        ind2Layout.setHorizontalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind2Layout.setVerticalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        profileBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileBtnLabel.setText("Work sites");

        javax.swing.GroupLayout sidePanelBtnProfileLayout = new javax.swing.GroupLayout(sidePanelBtnProfile);
        sidePanelBtnProfile.setLayout(sidePanelBtnProfileLayout);
        sidePanelBtnProfileLayout.setHorizontalGroup(
            sidePanelBtnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelBtnProfileLayout.createSequentialGroup()
                .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(profileBtnLabel)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        sidePanelBtnProfileLayout.setVerticalGroup(
            sidePanelBtnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelBtnProfileLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(profileBtnLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidePanel.add(sidePanelBtnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        sidePanelBtnSettings.setBackground(new java.awt.Color(23, 35, 51));
        sidePanelBtnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelBtnSettingsMousePressed(evt);
            }
        });

        ind3.setBackground(new java.awt.Color(204, 204, 204));
        ind3.setOpaque(false);
        ind3.setPreferredSize(new java.awt.Dimension(3, 50));

        javax.swing.GroupLayout ind3Layout = new javax.swing.GroupLayout(ind3);
        ind3.setLayout(ind3Layout);
        ind3Layout.setHorizontalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind3Layout.setVerticalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        settingsBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtnLabel.setText("Settings");

        javax.swing.GroupLayout sidePanelBtnSettingsLayout = new javax.swing.GroupLayout(sidePanelBtnSettings);
        sidePanelBtnSettings.setLayout(sidePanelBtnSettingsLayout);
        sidePanelBtnSettingsLayout.setHorizontalGroup(
            sidePanelBtnSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelBtnSettingsLayout.createSequentialGroup()
                .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(settingsBtnLabel)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        sidePanelBtnSettingsLayout.setVerticalGroup(
            sidePanelBtnSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelBtnSettingsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(settingsBtnLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        sidePanel.add(sidePanelBtnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 810));

        header.setBackground(new java.awt.Color(71, 120, 197));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        searchField.setBackground(new java.awt.Color(123, 156, 225));
        searchField.setForeground(new java.awt.Color(255, 255, 255));
        searchField.setBorder(null);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_32px.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(742, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn)
                .addGap(12, 12, 12))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1000, 90));
        getContentPane().add(dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));
        getContentPane().add(loginScreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));
        getContentPane().add(workSiteDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void sidePanelBtnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelBtnHomeMousePressed
        setColor(sidePanelBtnHome);
        ind.setOpaque(true);
        resetColor(new JPanel[]{sidePanelBtnUsers,sidePanelBtnProfile,sidePanelBtnSettings},new JPanel[]{ind1,ind2,ind3});
    }//GEN-LAST:event_sidePanelBtnHomeMousePressed

    private void sidePanelBtnUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelBtnUsersMousePressed
        setColor(sidePanelBtnUsers);
        ind1.setOpaque(true);
        resetColor(new JPanel[]{sidePanelBtnHome,sidePanelBtnProfile,sidePanelBtnSettings},new JPanel[]{ind,ind2,ind3});
    }//GEN-LAST:event_sidePanelBtnUsersMousePressed

    private void sidePanelBtnProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelBtnProfileMousePressed
        setColor(sidePanelBtnProfile);
        ind2.setOpaque(true);
        resetColor(new JPanel[]{sidePanelBtnUsers,sidePanelBtnHome,sidePanelBtnSettings},new JPanel[]{ind1,ind,ind3});
    }//GEN-LAST:event_sidePanelBtnProfileMousePressed

    private void sidePanelBtnSettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelBtnSettingsMousePressed
        setColor(sidePanelBtnSettings);
        ind3.setOpaque(true);
        resetColor(new JPanel[]{sidePanelBtnUsers,sidePanelBtnProfile,sidePanelBtnHome},new JPanel[]{ind1,ind2,ind});
    }//GEN-LAST:event_sidePanelBtnSettingsMousePressed

    int xx,xy;
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    private void setColor(JPanel pane){
        pane.setBackground(new Color(41,57,80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators){
        for(JPanel panel : pane){
            panel.setBackground(new Color(23,35,51));
        }
        for(JPanel indicator : indicators){
            indicator.setOpaque(false);
        }
    }

    public void login(){
        //loginScreen1.setVisible(false);
        updateDashboard();
    }

    private void updateDashboard(){
        if(dashboard2.isVisible()){
            dashboard2.setVisible(false);
        }else{
            dashboard2.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Dashboard dashboard2;
    private javax.swing.JPanel header;
    private javax.swing.JLabel homeBtnLabel;
    private javax.swing.JPanel ind;
    private javax.swing.JPanel ind1;
    private javax.swing.JPanel ind2;
    private javax.swing.JPanel ind3;
    private loginScreen loginScreen2;
    private javax.swing.JLabel profileBtnLabel;
    private javax.swing.JLabel searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel settingsBtnLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sidePanelBtnHome;
    private javax.swing.JPanel sidePanelBtnProfile;
    private javax.swing.JPanel sidePanelBtnSettings;
    private javax.swing.JPanel sidePanelBtnUsers;
    private javax.swing.JLabel usersBtnLabel;
    private workSiteDashboard workSiteDashboard1;
    // End of variables declaration//GEN-END:variables
}
