/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author dmich
 */
public class ViewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmployee
     */
    public ViewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        topBar3 = new javax.swing.JPanel();
        maximizeBtn3 = new javax.swing.JLabel();
        exitBtn3 = new javax.swing.JLabel();
        minimizeBtn3 = new javax.swing.JLabel();
        frameTitle3 = new javax.swing.JLabel();
        profilePicture = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        fnameValue = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        lnameValue = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        dobValue = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        sexValue = new javax.swing.JLabel();
        postalCodeLabel = new javax.swing.JLabel();
        postalCodeValue = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phoneValue = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressValue = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        countryValue = new javax.swing.JLabel();
        cprLabel = new javax.swing.JLabel();
        cprValue = new javax.swing.JLabel();
        scrollableSeasonalWorkers = new javax.swing.JScrollPane();
        seasonalWorkersList = new javax.swing.JList<>();
        scrollabelPaymentSlips = new javax.swing.JScrollPane();
        paymentslipsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Employee");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainContainer.setBackground(new java.awt.Color(23, 35, 51));

        topBar3.setBackground(new java.awt.Color(120, 168, 252));

        maximizeBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_maximize_button_32px.png"))); // NOI18N

        exitBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_close_window_32px.png"))); // NOI18N

        minimizeBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_minimize_window_32px_1.png"))); // NOI18N
        minimizeBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeBtn3MousePressed(evt);
            }
        });

        frameTitle3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        frameTitle3.setText("CS Works");

        javax.swing.GroupLayout topBar3Layout = new javax.swing.GroupLayout(topBar3);
        topBar3.setLayout(topBar3Layout);
        topBar3Layout.setHorizontalGroup(
                topBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBar3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(frameTitle3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minimizeBtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maximizeBtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitBtn3)
                                .addContainerGap())
        );
        topBar3Layout.setVerticalGroup(
                topBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBar3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(topBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(frameTitle3)
                                        .addGroup(topBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(minimizeBtn3)
                                                .addComponent(exitBtn3)
                                                .addComponent(maximizeBtn3)))
                                .addContainerGap())
        );

        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_github_96px.png"))); // NOI18N
        profilePicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profilePictureMousePressed(evt);
            }
        });

        fnameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fnameLabel.setText("Firstname:");

        fnameValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fnameValue.setForeground(new java.awt.Color(255, 255, 255));
        fnameValue.setText("John");

        lnameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lnameLabel.setText("Lastname:");

        lnameValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lnameValue.setForeground(new java.awt.Color(255, 255, 255));
        lnameValue.setText("Doe");

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");

        emailValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailValue.setForeground(new java.awt.Color(255, 255, 255));
        emailValue.setText("mymail@email.me");

        dobLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(255, 255, 255));
        dobLabel.setText("Date of birth:");

        dobValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dobValue.setForeground(new java.awt.Color(255, 255, 255));
        dobValue.setText("08/08/1985");

        sexLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(255, 255, 255));
        sexLabel.setText("Sex:");

        sexValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sexValue.setForeground(new java.awt.Color(255, 255, 255));
        sexValue.setText("M");

        postalCodeLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        postalCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLabel.setText("Postal code:");

        postalCodeValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        postalCodeValue.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeValue.setText("9000");

        phoneLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone:");

        phoneValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneValue.setForeground(new java.awt.Color(255, 255, 255));
        phoneValue.setText("+45 12345678");

        addressLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Address: ");

        addressValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addressValue.setForeground(new java.awt.Color(255, 255, 255));
        addressValue.setText("Sofiendalsvej 16");

        countryLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        countryLabel.setForeground(new java.awt.Color(255, 255, 255));
        countryLabel.setText("Country:");

        countryValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        countryValue.setForeground(new java.awt.Color(255, 255, 255));
        countryValue.setText("Denmark");

        cprLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cprLabel.setForeground(new java.awt.Color(255, 255, 255));
        cprLabel.setText("CPR:");

        cprValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cprValue.setForeground(new java.awt.Color(255, 255, 255));
        cprValue.setText("0808854422");

        seasonalWorkersList.setBackground(new java.awt.Color(23, 35, 51));
        seasonalWorkersList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seasonal Workers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        seasonalWorkersList.setForeground(new java.awt.Color(255, 255, 255));
        seasonalWorkersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollableSeasonalWorkers.setViewportView(seasonalWorkersList);

        paymentslipsList.setBackground(new java.awt.Color(23, 35, 51));
        paymentslipsList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paymentslips", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        paymentslipsList.setForeground(new java.awt.Color(255, 255, 255));
        paymentslipsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollabelPaymentSlips.setViewportView(paymentslipsList);

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
                mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(topBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(profilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fnameLabel)
                                                        .addComponent(lnameLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fnameValue)
                                                        .addComponent(lnameValue)))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(emailLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(emailValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(dobLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dobValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(sexLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sexValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(phoneLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(phoneValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(addressLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addressValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(postalCodeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(postalCodeValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(countryLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(countryValue))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(cprLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cprValue)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollabelPaymentSlips, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scrollableSeasonalWorkers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        mainContainerLayout.setVerticalGroup(
                mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addComponent(topBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(profilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(fnameLabel)
                                                                        .addComponent(fnameValue))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lnameLabel)
                                                                        .addComponent(lnameValue))))
                                                .addGap(18, 18, 18)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLabel)
                                                        .addComponent(emailValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dobLabel)
                                                        .addComponent(dobValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(sexLabel)
                                                        .addComponent(sexValue)))
                                        .addComponent(scrollableSeasonalWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(phoneValue)
                                                        .addComponent(phoneLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(addressLabel)
                                                        .addComponent(addressValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(postalCodeLabel)
                                                        .addComponent(postalCodeValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(countryLabel)
                                                        .addComponent(countryValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cprLabel)
                                                        .addComponent(cprValue)))
                                        .addComponent(scrollabelPaymentSlips, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void minimizeBtn3MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void profilePictureMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressValue;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel countryValue;
    private javax.swing.JLabel cprLabel;
    private javax.swing.JLabel cprValue;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel dobValue;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailValue;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel exitBtn1;
    private javax.swing.JLabel exitBtn2;
    private javax.swing.JLabel exitBtn3;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel fnameValue;
    private javax.swing.JLabel frameTitle;
    private javax.swing.JLabel frameTitle1;
    private javax.swing.JLabel frameTitle2;
    private javax.swing.JLabel frameTitle3;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JLabel lnameValue;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JLabel maximizeBtn;
    private javax.swing.JLabel maximizeBtn1;
    private javax.swing.JLabel maximizeBtn2;
    private javax.swing.JLabel maximizeBtn3;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel minimizeBtn1;
    private javax.swing.JLabel minimizeBtn2;
    private javax.swing.JLabel minimizeBtn3;
    private javax.swing.JList<String> paymentslipsList;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneValue;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JLabel postalCodeValue;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JScrollPane scrollabelPaymentSlips;
    private javax.swing.JScrollPane scrollableSeasonalWorkers;
    private javax.swing.JList<String> seasonalWorkersList;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel sexValue;
    private javax.swing.JPanel topBar;
    private javax.swing.JPanel topBar1;
    private javax.swing.JPanel topBar2;
    private javax.swing.JPanel topBar3;
    // End of variables declaration
}
