/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author dmich
 */
public class WorkSiteDashboard extends javax.swing.JPanel {

    /**
     * Creates new form WorkSiteDashboard
     */

    private final MainScreen mainScreen;

    public WorkSiteDashboard(MainScreen mainScreen) {
        this.mainScreen = mainScreen;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        taskTitle = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        scrollablePanel = new javax.swing.JScrollPane();
        listContainer = new javax.swing.JPanel();
        listElement1 = new javax.swing.JPanel();
        personName = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        editBtn2 = new javax.swing.JButton();
        createWorkSite = new javax.swing.JButton();
        searchWorkSite = new javax.swing.JButton();
        editWorkSite = new javax.swing.JButton();
        removeWorkSite = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(120, 168, 252));
        topBar.setPreferredSize(new java.awt.Dimension(1000, 110));

        taskTitle.setBackground(new java.awt.Color(249, 249, 249));
        taskTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        taskTitle.setForeground(new java.awt.Color(249, 249, 249));
        taskTitle.setText("CSWorks work sites");
        taskTitle.setPreferredSize(new java.awt.Dimension(450, 50));

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
                topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topBarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(taskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(520, Short.MAX_VALUE))
        );
        topBarLayout.setVerticalGroup(
                topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topBarLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(taskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainContainer.setBackground(new java.awt.Color(71, 120, 197));

        scrollablePanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollablePanel.setMinimumSize(new java.awt.Dimension(900, 600));

        listContainer.setBackground(new java.awt.Color(71, 120, 197));
        listContainer.setMinimumSize(new java.awt.Dimension(900, 600));
        listContainer.setPreferredSize(new java.awt.Dimension(1000, 700));

        listElement1.setBackground(new java.awt.Color(23, 35, 51));
        listElement1.setPreferredSize(new java.awt.Dimension(865, 112));

        personName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        personName.setText("Company for testing");

        editBtn.setBackground(new java.awt.Color(23, 35, 51));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_eye_32px.png"))); // NOI18N
        editBtn.setText("View");

        editBtn1.setBackground(new java.awt.Color(23, 35, 51));
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_edit_32px.png"))); // NOI18N
        editBtn1.setText("Edit");

        editBtn2.setBackground(new java.awt.Color(23, 35, 51));
        editBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_trash_can_32px.png"))); // NOI18N
        editBtn2.setText("Remove");

        javax.swing.GroupLayout listElement1Layout = new javax.swing.GroupLayout(listElement1);
        listElement1.setLayout(listElement1Layout);
        listElement1Layout.setHorizontalGroup(
                listElement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listElement1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(personName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        listElement1Layout.setVerticalGroup(
                listElement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listElement1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(listElement1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editBtn)
                                        .addComponent(personName)
                                        .addComponent(editBtn1)
                                        .addComponent(editBtn2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listContainerLayout = new javax.swing.GroupLayout(listContainer);
        listContainer.setLayout(listContainerLayout);
        listContainerLayout.setHorizontalGroup(
                listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listContainerLayout.createSequentialGroup()
                                .addComponent(listElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 359, Short.MAX_VALUE))
        );
        listContainerLayout.setVerticalGroup(
                listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listContainerLayout.createSequentialGroup()
                                .addComponent(listElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 640, Short.MAX_VALUE))
        );

        scrollablePanel.setViewportView(listContainer);

        createWorkSite.setBackground(new java.awt.Color(71, 120, 197));
        createWorkSite.setForeground(new java.awt.Color(255, 255, 255));
        createWorkSite.setText("Create work site");
        createWorkSite.setBorder(null);
        createWorkSite.setBorderPainted(false);
        createWorkSite.setContentAreaFilled(false);
        createWorkSite.setFocusPainted(false);
        createWorkSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createWorkSiteActionPerformed(evt);
            }
        });

        searchWorkSite.setBackground(new java.awt.Color(71, 120, 197));
        searchWorkSite.setForeground(new java.awt.Color(255, 255, 255));
        searchWorkSite.setText("Search work site");
        searchWorkSite.setBorder(null);
        searchWorkSite.setBorderPainted(false);
        searchWorkSite.setContentAreaFilled(false);
        searchWorkSite.setFocusPainted(false);
        searchWorkSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWorkSiteActionPerformed(evt);
            }
        });

        editWorkSite.setBackground(new java.awt.Color(71, 120, 197));
        editWorkSite.setForeground(new java.awt.Color(255, 255, 255));
        editWorkSite.setText("Edit work site");
        editWorkSite.setBorder(null);
        editWorkSite.setBorderPainted(false);
        editWorkSite.setContentAreaFilled(false);
        editWorkSite.setFocusPainted(false);
        editWorkSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWorkSiteActionPerformed(evt);
            }
        });

        removeWorkSite.setBackground(new java.awt.Color(71, 120, 197));
        removeWorkSite.setForeground(new java.awt.Color(255, 255, 255));
        removeWorkSite.setText("Remove work site");
        removeWorkSite.setBorder(null);
        removeWorkSite.setBorderPainted(false);
        removeWorkSite.setContentAreaFilled(false);
        removeWorkSite.setFocusPainted(false);
        removeWorkSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeWorkSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
                mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addComponent(createWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(scrollablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                        .addGroup(mainContainerLayout.createSequentialGroup()
                                                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(searchWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(editWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(removeWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(693, 693, 693))))
        );
        mainContainerLayout.setVerticalGroup(
                mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(mainContainerLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(createWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(searchWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(editWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(removeWorkSite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(160, Short.MAX_VALUE))
        );

        add(mainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1000, 610));
    }// </editor-fold>

    private void createWorkSiteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void searchWorkSiteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void editWorkSiteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void removeWorkSiteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton createWorkSite;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton editBtn2;
    private javax.swing.JButton editWorkSite;
    private javax.swing.JPanel listContainer;
    private javax.swing.JPanel listElement;
    private javax.swing.JPanel listElement1;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JLabel personName;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JButton removeWorkSite;
    private javax.swing.JScrollPane scrollablePanel;
    private javax.swing.JButton searchWorkSite;
    private javax.swing.JLabel taskTitle;
    private javax.swing.JPanel topBar;
    // End of variables declaration
}
